name: Check formatting via prettier

on:
  pull_request:
    branches: ["master"]
jobs:
  check-formatting-via-prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install prettier
        run: npm i prettier prettier-plugin-tailwindcss @trivago/prettier-plugin-sort-imports

      - name: Check prettier
        run: npx prettier --check .
